---

extends:
- airbnb-base
- 'plugin:jest/recommended'

parser: babel-eslint

plugins:
- jest

rules:
  "comma-dangle": 0
  "func-names": 0
  "no-underscore-dangle": 0

env:
  node: true
  jest/globals: true
